# Server configurations
server:
  port: :8080

# Application specific configurations
application:
  name: WebAPI
  doc: http://localhost:8080

logging:
  level: DEBUG
secret:
  Key: "Test"

#Note: Please change the credentials according to your connection
#MYSQL Crendentials 
mysql:
  user : "root"
  password : "password"
  host: "127.0.0.1"
  port : "3306"
  dbname : "SondrApp"