# Server configurations
server:
  port: :8080

# Application specific configurations
application:
  name: WebAPI
  doc: http://localhost:8080


logging:
  level: DEBUG

#MYSQL Crendentials NOTE: THIS HAS TO BE MODIFIED BASED ON THE USERS 
mysql:
  user : "root"
  password : "P@ssword123"
  host: "127.0.0.1"
  port : "3306"
  dbname : "ALERTS"